services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Schwarzenegger
      POSTGRES_DB: laundry
    ports:
      - "5432:5432"
    profiles:
      - infrastructure


